Feature/button component
isdi-coders-2023/coding-adventure-Sergio-Fontal-front-202301-BCN pull request #1
Opened 2023-02-27 16:39 UTC by SFontal

- Button component
- Button styles
- Button test
- GlobalStyles
- Install Styled-Components
- Install saira-stencil-one font

2023-02-27 16:42 UTC, benjaminrae requested changes

2023-02-27 16:42 UTC, benjaminrae commented on src/components/Button/ButtonStyled.tsx
> +  background-color: #cccf18;
Vamos a repetir los colores en todos los componentes? Deberias extraerlos a un unico lugar.

2023-02-27 16:42 UTC, benjaminrae commented on src/components/Button/ButtonStyled.tsx
> +const ButtonStyled = styled.button`
Este componente no tiene estilos para cuando este disabled

2023-02-27 16:42 UTC, benjaminrae commented on src/styles/GlobalStyles.tsx
> +const GlobalStyles = createGlobalStyle`
No hay mas cosas que podrias meter en el reset?

2023-02-27 16:42 UTC, benjaminrae commented on src/styles/GlobalStyles.tsx
> +*,
Pones margin y padding a todos los elementos aqui, va a generar mucho ruido

2023-02-27 16:50 UTC, SFontal commented on src/components/Button/ButtonStyled.tsx
> +  background-color: #cccf18;
De acuerdo.

2023-02-27 16:50 UTC, SFontal commented on src/components/Button/ButtonStyled.tsx
> +const ButtonStyled = styled.button`
Ok. Lo añado.

2023-02-27 16:50 UTC, SFontal commented on src/styles/GlobalStyles.tsx
> +const GlobalStyles = createGlobalStyle`
Por ahora no se me ocurre nada. Lo miro.

2023-02-27 16:51 UTC, SFontal commented on src/styles/GlobalStyles.tsx
> +*,
Creo que es lo que venimos haciendo hasta ahora. ¿Debería aplicarlo únicamente al body?

2023-02-27 17:25 UTC, benjaminrae commented on src/styles/GlobalStyles.tsx
> +*,
Ha salido en code reviews que al selector universal no queremos meter ruido

2023-02-28 11:46 UTC, MMLORENA submitted a review, later dismissed

2023-02-28 11:46 UTC, MMLORENA commented on src/components/Button/Button.test.tsx
> +      const text = "Sign up";
Enter

2023-02-28 11:46 UTC, MMLORENA commented on src/components/Button/ButtonStyled.tsx
> +  font-family: "Saira Stencil One";
Las fuentes y las variables deberían estar en los styles generales

2023-02-28 12:49 UTC, SFontal commented on src/components/Button/Button.test.tsx
> +      const text = "Sign up";
Enterado. Gracias. :)

2023-02-28 12:50 UTC, SFontal commented on src/components/Button/ButtonStyled.tsx
> +  font-family: "Saira Stencil One";
Sí. Lo acabo de solucionar. Gracias. :)

2023-02-28 14:15 UTC, catatarelli approved these changes

2023-02-28 14:17 UTC, merged